/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algebra;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        // Valores por default.

        Col3.setActionCommand("3");
        Col3.setSelected(true);
        Fil3.setActionCommand("3");
        Fil3.setSelected(true);
        
        Fil1.setVisible(false);
        Col1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Columnas = new javax.swing.ButtonGroup();
        Filas = new javax.swing.ButtonGroup();
        OperacionesElementales = new javax.swing.JButton();
        EcuacionesMatriciales = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Col1 = new javax.swing.JRadioButton();
        Col2 = new javax.swing.JRadioButton();
        Col3 = new javax.swing.JRadioButton();
        Col4 = new javax.swing.JRadioButton();
        Col5 = new javax.swing.JRadioButton();
        Fil1 = new javax.swing.JRadioButton();
        Fil2 = new javax.swing.JRadioButton();
        Fil3 = new javax.swing.JRadioButton();
        Fil4 = new javax.swing.JRadioButton();
        Fil5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        OperacionesElementales.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OperacionesElementales.setText("Operaciones elementales");
        OperacionesElementales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperacionesElementalesActionPerformed(evt);
            }
        });

        EcuacionesMatriciales.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EcuacionesMatriciales.setText("Ecuaciones matriciales");
        EcuacionesMatriciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EcuacionesMatricialesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cantidad de filas:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Cantidad de columnas:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Álgebra Matricial");

        Columnas.add(Col1);
        Col1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Col1.setText("1");
        Col1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Col1ActionPerformed(evt);
            }
        });

        Columnas.add(Col2);
        Col2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Col2.setText("2");
        Col2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Col2ActionPerformed(evt);
            }
        });

        Columnas.add(Col3);
        Col3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Col3.setText("3");
        Col3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Col3ActionPerformed(evt);
            }
        });

        Columnas.add(Col4);
        Col4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Col4.setText("4");
        Col4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Col4ActionPerformed(evt);
            }
        });

        Columnas.add(Col5);
        Col5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Col5.setText("5");
        Col5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Col5ActionPerformed(evt);
            }
        });

        Filas.add(Fil1);
        Fil1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Fil1.setText("1");
        Fil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fil1ActionPerformed(evt);
            }
        });

        Filas.add(Fil2);
        Fil2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Fil2.setText("2");
        Fil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fil2ActionPerformed(evt);
            }
        });

        Filas.add(Fil3);
        Fil3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Fil3.setText("3");
        Fil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fil3ActionPerformed(evt);
            }
        });

        Filas.add(Fil4);
        Fil4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Fil4.setText("4");
        Fil4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fil4ActionPerformed(evt);
            }
        });

        Filas.add(Fil5);
        Fil5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Fil5.setText("5");
        Fil5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fil5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(OperacionesElementales)
                                .addGap(13, 13, 13)
                                .addComponent(EcuacionesMatriciales))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Fil1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Fil2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Fil3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Fil4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Fil5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Col1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Col2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Col3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Col4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Col5)))))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Fil1)
                        .addComponent(Fil2)
                        .addComponent(Fil3)
                        .addComponent(Fil4)
                        .addComponent(Fil5))
                    .addComponent(jLabel1))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Col1)
                    .addComponent(Col2)
                    .addComponent(Col3)
                    .addComponent(Col4)
                    .addComponent(Col5))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OperacionesElementales)
                    .addComponent(EcuacionesMatriciales))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OperacionesElementalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperacionesElementalesActionPerformed
        // Obtiene cantidad de columnas deseadas.
        
        short colSeleccionadas = Short.parseShort(Columnas.getSelection().getActionCommand());
        short filSeleccionadas = Short.parseShort(Filas.getSelection().getActionCommand());
        
        Main.matrizCol = colSeleccionadas;
        Main.matrizFil = filSeleccionadas;
       
        // Inicia VentanaOperaciones.
        this.setVisible(false); // Oculta esta ventana.
        VentanaOperaciones VentanaOperaciones_ = new VentanaOperaciones();
        VentanaOperaciones_.setVisible(true);
        VentanaOperaciones_.setResizable(false); // Tamaño de ventana no variable.
        VentanaOperaciones_.setLocationRelativeTo(null); // Centra ventana.
    }//GEN-LAST:event_OperacionesElementalesActionPerformed

    private void EcuacionesMatricialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EcuacionesMatricialesActionPerformed
        short colSeleccionadas = Short.parseShort(Columnas.getSelection().getActionCommand());
        short filSeleccionadas = Short.parseShort(Filas.getSelection().getActionCommand());
        
        if(colSeleccionadas != filSeleccionadas || filSeleccionadas == 1) {
            JOptionPane.showMessageDialog(null, "Error: deben ser matrices cuadradas >= 2.");
            return;
        }
        
        Main.matrizCol = colSeleccionadas;
        Main.matrizFil = filSeleccionadas;
        
        // Inicia VentanaOperaciones.
        this.setVisible(false); // Oculta esta ventana.
        VentanaEcuaciones VentanaEcuaciones_ = new VentanaEcuaciones();
        VentanaEcuaciones_.setVisible(true);
        VentanaEcuaciones_.setResizable(false); // Tamaño de ventana no variable.
        VentanaEcuaciones_.setLocationRelativeTo(null); // Centra ventana.
    }//GEN-LAST:event_EcuacionesMatricialesActionPerformed

    private void Col1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Col1ActionPerformed
        Col1.setActionCommand("1");
    }//GEN-LAST:event_Col1ActionPerformed

    private void Col2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Col2ActionPerformed
        Col2.setActionCommand("2");
    }//GEN-LAST:event_Col2ActionPerformed

    private void Col3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Col3ActionPerformed
        Col3.setActionCommand("3");
    }//GEN-LAST:event_Col3ActionPerformed

    private void Col4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Col4ActionPerformed
        Col4.setActionCommand("4");
    }//GEN-LAST:event_Col4ActionPerformed

    private void Col5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Col5ActionPerformed
        Col5.setActionCommand("5");
    }//GEN-LAST:event_Col5ActionPerformed

    private void Fil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fil1ActionPerformed
        Fil1.setActionCommand("1");
    }//GEN-LAST:event_Fil1ActionPerformed

    private void Fil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fil2ActionPerformed
        Fil2.setActionCommand("2");
    }//GEN-LAST:event_Fil2ActionPerformed

    private void Fil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fil3ActionPerformed
        Fil3.setActionCommand("3");
    }//GEN-LAST:event_Fil3ActionPerformed

    private void Fil4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fil4ActionPerformed
        Fil4.setActionCommand("4");
    }//GEN-LAST:event_Fil4ActionPerformed

    private void Fil5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fil5ActionPerformed
        Fil5.setActionCommand("5");
    }//GEN-LAST:event_Fil5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Col1;
    private javax.swing.JRadioButton Col2;
    private javax.swing.JRadioButton Col3;
    private javax.swing.JRadioButton Col4;
    private javax.swing.JRadioButton Col5;
    private javax.swing.ButtonGroup Columnas;
    private javax.swing.JButton EcuacionesMatriciales;
    private javax.swing.JRadioButton Fil1;
    private javax.swing.JRadioButton Fil2;
    private javax.swing.JRadioButton Fil3;
    private javax.swing.JRadioButton Fil4;
    private javax.swing.JRadioButton Fil5;
    private javax.swing.ButtonGroup Filas;
    private javax.swing.JButton OperacionesElementales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
